[package]
name = "random_walk_1d"
version = "0.1.0"
authors = ["jatsekku"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
streaming-stats = "0.1.28"
gnuplot = "0.0.37"
linreg = "0.2.0"
